### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by jr-cologne** [jr-cologne/jr-cologne.de#23]
I would like to turn my website into a PWA.

For this, I already set up the manifest file a while ago.

So, the only thing left should be to implement a Service Worker with a caching strategy like [Network or cache](https://serviceworke.rs/strategy-network-or-cache.html).

I would highly appreciate any contributions in order to push this issue forward.

In case you have any questions, do not hesitate to write a comment down below.

Once you are ready, make sure to fork this Repository.
Then, commit your changes to a branch called `your-username_pwa` and open up a Pull Request to merge your changes into this Repository.

Thank you & Happy coding! 🎉

**Comment by SanyasiraoM** [comment]
@jr-cologne I will take up this.

**Comment by jr-cologne** [comment]
Hi @SanyasiraoM,
there is already an existing PR (#24) regarding this.
If you still want to work on this, you can either help out in PR #24 or alternatively, you could also create your own PR.
But then, please keep in mind that your PR might not be the one I choose to merge in.
Thank you in advance and best regards,
@jr-cologne
